name = "laburen-challenge-aiengineer"
main = "src/index.ts"
compatibility_date = "2024-02-14"

[[d1_databases]]
binding = "DB"
database_name = "laburen-db"
database_id = "bd60acb1-fdeb-4bcc-a0d4-b5748a81ea9e"
